/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loteria;

import com.mycompany.clases.ReproductorDeSonido;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author javie
 */
public class Register extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    private ReproductorDeSonido reproductor;

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tittleRegister = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        fieldNombreUsuario = new javax.swing.JTextField();
        fieldCorreo = new javax.swing.JTextField();
        fieldContraseña = new javax.swing.JPasswordField();
        fieldConfirmarContrasena = new javax.swing.JPasswordField();
        tittleUsername = new javax.swing.JLabel();
        tittleEmail = new javax.swing.JLabel();
        tittlePass = new javax.swing.JLabel();
        tittleConfirmPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 231, 176));

        tittleRegister.setBackground(new java.awt.Color(255, 153, 0));
        tittleRegister.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        tittleRegister.setForeground(new java.awt.Color(175, 109, 55));
        tittleRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleRegister.setText("Registrate");

        btnVolver.setBackground(new java.awt.Color(244, 120, 175));
        btnVolver.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(51, 0, 51));
        btnVolver.setText("Volver al menú");
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.setPreferredSize(new java.awt.Dimension(130, 30));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnRegistrarse.setBackground(new java.awt.Color(244, 120, 175));
        btnRegistrarse.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(51, 0, 51));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setBorder(null);
        btnRegistrarse.setBorderPainted(false);
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarse.setPreferredSize(new java.awt.Dimension(130, 30));
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        fieldNombreUsuario.setBackground(new java.awt.Color(244, 120, 175));

        fieldCorreo.setBackground(new java.awt.Color(244, 120, 175));

        fieldContraseña.setBackground(new java.awt.Color(244, 120, 175));
        fieldContraseña.setText("jPasswordField1");

        fieldConfirmarContrasena.setBackground(new java.awt.Color(244, 120, 175));
        fieldConfirmarContrasena.setText("jPasswordField1");

        tittleUsername.setBackground(new java.awt.Color(255, 153, 0));
        tittleUsername.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        tittleUsername.setForeground(new java.awt.Color(175, 109, 55));
        tittleUsername.setText("Nombre de usuario");

        tittleEmail.setBackground(new java.awt.Color(255, 153, 0));
        tittleEmail.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        tittleEmail.setForeground(new java.awt.Color(175, 109, 55));
        tittleEmail.setText("Correo electrónico");

        tittlePass.setBackground(new java.awt.Color(255, 153, 0));
        tittlePass.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        tittlePass.setForeground(new java.awt.Color(175, 109, 55));
        tittlePass.setText("Contraseña");

        tittleConfirmPass.setBackground(new java.awt.Color(255, 153, 0));
        tittleConfirmPass.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        tittleConfirmPass.setForeground(new java.awt.Color(175, 109, 55));
        tittleConfirmPass.setText("Confirmar contraseña");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tittleRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 208, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tittleUsername)
                            .addComponent(tittleEmail)
                            .addComponent(tittlePass)
                            .addComponent(tittleConfirmPass))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldCorreo)
                            .addComponent(fieldContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(fieldConfirmarContrasena)
                            .addComponent(fieldNombreUsuario))
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(345, 345, 345))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittleRegister)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tittleUsername))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tittleEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tittlePass)
                    .addComponent(fieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tittleConfirmPass)
                    .addComponent(fieldConfirmarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        if (reproductor != null) {
            reproductor.detener();
        }

        ReproductorDeSonido clipBoton = new ReproductorDeSonido();
        clipBoton.cargarSonido("src\\main\\resources\\button-124476.wav");
        clipBoton.reproducir();

        try {
            Thread.sleep(400);
        } catch (InterruptedException ex) {
            ex.printStackTrace();
        }

        close();
        new Principal().setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed

        if (reproductor != null) {
            reproductor.detener();
        }

        ReproductorDeSonido clipBoton = new ReproductorDeSonido();
        clipBoton.cargarSonido("src\\main\\resources\\button-124476.wav");
        clipBoton.reproducir();

        try {
            Thread.sleep(400);
        } catch (InterruptedException ex) {
            ex.printStackTrace();
        }
        
        String nombreUsuario = fieldNombreUsuario.getText().trim();
        String correo = fieldCorreo.getText().trim();
        String contrasena = new String(fieldContraseña.getPassword());
        String confirmarContrasena = new String(fieldConfirmarContrasena.getPassword());

        if (nombreUsuario.isEmpty() || correo.isEmpty() || contrasena.isEmpty() || confirmarContrasena.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, completa todos los campos",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!contrasena.equals(confirmarContrasena)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Las contraseñas no coinciden",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (contrasena.length() < 6) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La contraseña debe tener al menos 6 caracteres",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!correo.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El correo electrónico no es válido",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        com.mycompany.clases.UsuarioDAO dao = new com.mycompany.clases.UsuarioDAO();
        boolean registroExitoso = dao.registrarUsuario(nombreUsuario, correo, contrasena);

        if (registroExitoso) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Registro exitoso. Por favor, inicia sesión",
                    "Registro completado",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            close();
            new Login().setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al registrar usuario. El correo o nombre de usuario ya existe",
                    "Error de registro",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPasswordField fieldConfirmarContrasena;
    private javax.swing.JPasswordField fieldContraseña;
    private javax.swing.JTextField fieldCorreo;
    private javax.swing.JTextField fieldNombreUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tittleConfirmPass;
    private javax.swing.JLabel tittleEmail;
    private javax.swing.JLabel tittlePass;
    private javax.swing.JLabel tittleRegister;
    private javax.swing.JLabel tittleUsername;
    // End of variables declaration//GEN-END:variables
}
